// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-NrpowP77FHuwe9C3E8i9bBVRSE1T3H4',
    appId: '1:536736355710:web:cad86e523ad8d05e250f2f',
    messagingSenderId: '536736355710',
    projectId: 'stride-squad-1eab7',
    authDomain: 'stride-squad-1eab7.firebaseapp.com',
    storageBucket: 'stride-squad-1eab7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa4FFe3HYzWBbRqcsaPJO8UB2y5YBddEI',
    appId: '1:536736355710:android:d85edba8d0e845ca250f2f',
    messagingSenderId: '536736355710',
    projectId: 'stride-squad-1eab7',
    storageBucket: 'stride-squad-1eab7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCOMttxpuucVmbcYCTRrePU4_Zh5P_IBg',
    appId: '1:536736355710:ios:eaaff1ddeec60e01250f2f',
    messagingSenderId: '536736355710',
    projectId: 'stride-squad-1eab7',
    storageBucket: 'stride-squad-1eab7.appspot.com',
    iosBundleId: 'com.example.stridesquad1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCOMttxpuucVmbcYCTRrePU4_Zh5P_IBg',
    appId: '1:536736355710:ios:eaaff1ddeec60e01250f2f',
    messagingSenderId: '536736355710',
    projectId: 'stride-squad-1eab7',
    storageBucket: 'stride-squad-1eab7.appspot.com',
    iosBundleId: 'com.example.stridesquad1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-NrpowP77FHuwe9C3E8i9bBVRSE1T3H4',
    appId: '1:536736355710:web:44e51f66e0aedb4b250f2f',
    messagingSenderId: '536736355710',
    projectId: 'stride-squad-1eab7',
    authDomain: 'stride-squad-1eab7.firebaseapp.com',
    storageBucket: 'stride-squad-1eab7.appspot.com',
  );
}
